# Generated by Django 5.0.6 on 2024-06-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
