# Generated by Django 5.0.6 on 2024-06-05 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.promocode'),
        ),
    ]
