# Generated by Django 5.0.6 on 2024-09-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vacancy_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='VidosEki/')),
                ('image', models.ImageField(upload_to='images/')),
                ('history', models.TextField()),
                ('details', models.TextField()),
                ('certificate', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
